baseURL = "https://www.example.com"
languageCode = "en-us"
title = "Hei world, it's Khang"
theme = "hugo-digital-garden-theme"
themesdir = "./themes"

copyright = "Khangruni ©"

[params]
  name = "Khang Nguyen Tran"
  description = "The sun comes up it's new day dawning, it's time to sing your song again."
  initials = "Khangruni"
  googleAnalytics = ""

  [[params.social]]
    name = "Twitter"
    link = "https://www.facebook.com/trankhang.nguyen.35/"
    icon = "fab fa-facebook"

  [[params.social]]
    name = "Github"
    link = "https://github.com/khangt1k25"
    icon = "fab fa-github"


  [[params.social]]
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/khang-nguyen-tran/"
    icon = "fab fa-linkedin-in"


[menu]
  [[menu.main]]
    name = "My Garden"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Tech"
    url = "/tech/"
    weight = 2
  [[menu.main]]
    name = "Library"
    url = "/library/"
    weight = 3
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 4
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 5


[taxonomies]
  garden_tags = 'garden_tags'
  project_tags = 'project_tags'
  library_tags = 'library_tags'


[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'