baseURL = "https://khangt1k25.github.io"
languageCode = "en-us"
title = "khangruni"
theme = ["hugo-digital-garden-theme2"]
themesdir = "./themes"
disqusShortname = 'khangruni'

copyright = "Khangruni ©"

[params]
  name = "Khang Nguyen Tran"
  description = "The sun comes up it's new day dawning, it's time to sing your song again."
  initials = "Khangruni"
  googleAnalytics = "G-GPVC98SDG9"
  
    
  [[params.social]]
    name = "Github"
    link = "https://github.com/khangt1k25"
    icon = "fab fa-github"

  [[params.social]] 
    name = "LinkedIn"
    link = "https://www.linkedin.com/in/khang-nguyen-tran/"
    icon = "fab fa-linkedin-in"

  [[params.social]] 
    name = "Email"
    link = "mailto:khangruni@gmail.com"
    icon = "fas fa-envelope"


[menu]
  [[menu.main]]
    name = "My Garden"
    url = "/garden/"
    weight = 1
  [[menu.main]]
    name = "Tech"
    url = "/tech/"
    weight = 2
  [[menu.main]]
    name = "Book"
    url = "/book/"
    weight = 3
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 4
  [[menu.main]]
    name = "Gallery"
    url = "/gallery/"
    weight = 5
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 6


[taxonomies]
  garden_tags = 'garden_tags'
  tech_tags = 'tech_tags'
  book_tags = 'book_tags'
  

  
[markup]
  defaultMarkdownHandler = 'goldmark'
  [markup.goldmark.renderer]
    unsafe = true
  [markup.goldmark.extensions]
    definitionList = true
    footnote = true
    linkify = true
    strikethrough = true
    table = true
    taskList = true
    typographer = true
  [markup.highlight]
    # Choose from https://xyproto.github.io/splash/docs/all.html
    style = 'monokailight'